name: metaeval
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - ca-certificates=2023.7.22
  - intel-openmp=2023.1.0
  - joblib=1.3.2
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libstdcxx-ng=11.2.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.7
  - openssl=3.0.11
  - pandas=2.0.3
  - pip=23.2.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3.post1
  - readline=8.2
  - scikit-learn=1.0.2
  - scipy=1.8.1
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - dtw-python==1.3.0
      - h5py==3.10.0
      - numpy==1.24.4
